### PR TITLE
Adding `AudioObject` and minor corrections

### PR DESCRIPTION
**Pull request by wareid**
Adding the usage of `AudioObject` for items in the readingOrder. After reviewing the `AudioObject` in schema.org I think this is a grat type option for reading order items, it gives us all of the attributes we need.

***
<a href="https://pr-preview.s3.amazonaws.com/wareid/audiobooks/pull/4.html" title="Last updated on Jun 11, 2019, 3:33 PM UTC (acfd09e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/4/58932bb...wareid:acfd09e.html" title="Last updated on Jun 11, 2019, 3:33 PM UTC (acfd09e)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
The resources should have a dual type then:

```json
"type" : ["LinkedResource", "AudioObject"]
```

The `resources` or `readingOrder` terms are defined to refer to an array of `LinkedResource` object, hence the necessity to keep those. Besides, we may have properties (like integrity) that the AudioObject does not have...

**Comment by wareid** [comment]
@iherman I have changed it just to be LinkedResource for now with a note, can you review?

**Comment by iherman** [comment]
@wareid you may want to turn the AudioBook reference to an active link to the schema.org object to make it clear that this is what we are talking about. Otherwise, as far as I am concerned, it is a go!

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-06-10-pwg#section2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
audiobooks<br/>
Wendy Reid: <a href="https://github.com/w3c/audiobooks/pull/4">https://github.com/w3c/audiobooks/pull/4</a><br/>
Wendy Reid: I’ve done a pr for audiobooks<br/>
… this adds audioObject as discussed at f2f<br/>
… if everyone’s ok, we can merge this and then do fpwd<br/>
Ivan Herman: I have comment on pr<br/>
… which is essential<br/>
… right now doc says all things in reading order must be audio object<br/>
… which conflicts with wpub<br/>
… it should be possible to do both<br/>
Laurent Le Meur: in example in wp spec<br/>
… in c3, audiobook example, there is no type property on link object<br/>
… but ivan insists the type should be there<br/>
… should we in all examples add <code>@type</code><br/>
… or should we decide that <code>@type</code> is optional<br/>
Ivan Herman: two things<br/>
… first, current situation is that canonicalization would add link type<br/>
… the reason that type is there, what happens is that schema.org complains if type for person is not there<br/>
… it’s required by schema.org<br/>
… we could decide it’s not required, but then we create an asymmetry<br/>
… and if schema.org later creates such a type, then we have a problem<br/>
Benjamin Young: have we considered getting linked resource into schema?<br/>
… it looks like a superset of most of what we need<br/>
Ivan Herman: there is an open issue somewhere<br/>
… the answer is yes and no<br/>
… there is an object defined by schema which is close to what we need<br/>
… and I raised this issue<br/>
… but there’s no way to add <code>@rel</code> to that object<br/>
… and it hasn’t been changed<br/>
… we should have a comment in our doc that this may disappear in favor of ?<br/>
Wendy Reid: we have a growing list of issues for schema.org<br/>
… we should be logging github issues and then emailing notifications<br/>
Ivan Herman: i’m happy to do so<br/>
Wendy Reid: in the meantime we don’t want this to stop us<br/>
Laurent Le Meur: we have a slight issue<br/>
… the link object has its own way to reference content<br/>
… and the audio object has a different way<br/>
… maybe we should add note to audio spec saying we’ll use properties from audio object<br/>
Wendy Reid: apparently we can map attributes like that<br/>
… so we could continue using url and have it map to content url<br/>
… so we stay consistent but schema is still happy<br/>
Benjamin Young: you can do that, but schema would be unhappy<br/>
Tim Cole: +1 bigbluehat<br/>
Benjamin Young: it’s like linking to a video–youtube has a video url to the page, but the content url is to the video format itself<br/>
Tim Cole: But might be a way to call their attention to this<br/>
Ivan Herman: but if we keep both for very good reasons then I think that the fpwd should make it clear why we do that<br/>
… what benjamin just said should be made clear for the reader<br/>
Benjamin Young: it could be in processing instructions for implementers<br/>
… then use content url even if there is also url<br/>
Wendy Reid: maybe we should hold off on audio object until we talk to schema<br/>
… I also see spec is using media object<br/>
Ivan Herman: it’s fine to publish fpwd without audio object, but have reference to the issue<br/>
… we need fpwd soon<br/>
Wendy Reid: I won’t merge the pr<br/>
… I’ll switch from mediaobject to linked resource, and include a note<br/>
… and then we can publish, if people have no objects<br/>
Ivan Herman: for fpwd we need a resolution to publish, and specifies the short name<br/>
Wendy Reid: did we do that at f2f<br/>
Ivan Herman: i don’t remember<br/>
Wendy Reid: I think we have short name of audiobooks (can’t hear punctuation on the phone)<br/>
Ivan Herman: -> <a href="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg.html#resolution2">https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-05-06-pwg.html#resolution2</a> F2F resolution<br/>
Wendy Reid: i’ll do that this week<br/>
</details>

**Comment by wareid** [comment]
@iherman You mean in the Publication Type section? I have already put a link in to schema.org, or do you mean elsewhere?

**Comment by iherman** [comment]
You have a note in https://pr-preview.s3.amazonaws.com/wareid/audiobooks/pull/4.html#audio-readingorder which refers to AudioObject; this is the only place where this object is mentioned. I think it should link to schema.org/AudioObject.

**Pull request merged**
