### PR TITLE
First Draft of the Audiobooks Profile

### PR DESCRIPTION
**Pull request by wareid**
For review by PWG, here is the first (very rough) draft of the audiobooks profile. Please review and provide all the feedback you can, I am sure I have missed many things.

***
<a href="https://pr-preview.s3.amazonaws.com/wareid/audiobooks/pull/1.html" title="Last updated on Apr 1, 2019, 8:15 PM UTC (3c01559)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/audiobooks/1/29bd837...wareid:3c01559.html" title="Last updated on Apr 1, 2019, 8:15 PM UTC (3c01559)">Diff</a>

### CODE REVIEW

**Comment by wareid** [comment]
I think this is probably the best way to go, I completely forgot about the repo issue, so I’m happy to go ahead and merge so others can edit.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by llemeurfr** [comment]
Thanks a lot @wareid for this document. 

At this stage my main question to the group is: to which extend can we re-introduce in the audiobook spec information that is already defined in the Web Publications spec? the balance is delicate between the risk of duplicating specification and the need to have a document that is self readable. Sections about Bounds and Primary Entry Page are examples of this tension. Let's take the latter: we could modify it by making reference to the WP PEP specification and only state additional constraints like: The PEP cannot contain the content audio content; and the PEP cannot be included in the default reading order.  
Keeping in the Audiobook document only information specific to audiobooks will make the maintenance of the specifications easier (no duplication -> no double source of truth) but will make the audiobook spec a satellite of the mail WP spec, short but more like an annex than a spec. 

Link to the html preview: https://raw.githack.com/wareid/audiobooks/draft/index.html.

**Comment by iherman** [comment]
> Keeping in the Audiobook document only information specific to audiobooks will make the maintenance of the specifications easier (no duplication -> no double source of truth) but will make the audiobook spec a satellite of the mail WP spec, short but more like an annex than a spec.

This is true. A possible approach may be:

1. Keep the audiobook _spec_ indeed short and compact. I think that, with an eye for later developments of possible other profiles keeping it as a separate spec (albeit short) makes sense.
2. We may want to produce some sort of a primer/intro/whatever document that concentrates on those feature of both specs (plus the package one) to give an easy introduction to audiobooks.

**Comment by iherman** [comment]
An addendum to my previous comment https://github.com/w3c/audiobooks/pull/1#issuecomment-478322714: there may be a third option.

There are some W3C Recommendation track documents (e.g., [RDFa](https://www.w3.org/TR/rdfa-core/) or [JSON-LD](https://w3c.github.io/json-ld-syntax/)) that make some sort of a mixture of the two options above. They have a relatively long, _non normative_ introductory text that serves as an incomplete primer, and the second part of the spec is the normative text that define the necessary features. This may well be an approach here:

- Have a non-normative section providing a sketch of what is currently in the WPUB spec as far as the manifest is concerned
- Have a separate normative section defining what is, well, normative for audiobooks and which goes _beyond_ what WPUB already defines

**Comment by iherman** [comment]
Some comments on the content, mainly for the discussion on the next call. Results of the discussion might lead to separate issues or direct changes on the document...

2.2.3. Bounds

> An audiobook's manifest MUST define its Publication Type using the type term [json-ld]. The type MUST be Audiobook [schema.org].

- The value of `type` may be an array of types. Is it allowed to mix the `Audiobook` type with some other types of publications? What does that mean?
- Does the presence of an `Audiobook` type _defines_ an audiobook, or will there be some other means to denote a book to be an audiobook?

2.2.4.2 Creators

The text specifies that `author` and `readBy` are 'required'. On the other hand, the larger 'creator' category is defined as a "RECOMMENDED" but not a "REQUIRED" property in the WPUB. Does it mean that:

> An audiobook _MUST_ include an `author` and a `readBy` entry in the manifest, ie, the definition of an audiobook sharpens the general requirement of a WPUB.

If this is the requirement, then this fact must be made more explicit.

2.2.4.3 Duration

- Is it a 'duration' for the book as a whole or is it a duration for each individual audio resource? The various examples suggest both, but it should be said explicitly.
- The table refers (in the last column) to the Schema.org `datePublished` property. That should be, I presume, `https://pending.schema.org/duration`. Is it so?
    - if not, we have to define our own
    - if yes, note that it can also be used on `MediaObject` types, not only audio. Which is just fine, because I believe this property should be available for non-audio resources and books, too.
- Referring to the note above: this property may have to be pushed into the generic WPUB, to be used with other, non-audio objects as well.
- Is the usage of duration _REQUIRED_ for audio books, at least on the book as a whole? 

(Technical note: if we use schema.org, it means that the audio files should be denoted in the manifest as, also of type `MediaObject`)

2.2.4.4

> The default reading order MUST contain at least one audio resource.

I wonder... isn't the essence of an audiobook that _all_ resources in the reading order _must_ be audio files? Auxiliary materials can be put into the resource lists, of course.

If so, there is one consequence: the default setup whereby the PEP becomes the only entry in the reading order if the latter is not explicitly defined becomes invalid for audio books, and a reading order is _REQUIRED_ for audio books.

**Comment by wareid** [comment]
@iherman Added some changes based on your feedback, including a reference to the `duration` issue. 

@GarthConboy Can we merge this today to make the feedback process a little easier for anyone who wants to review?

**Pull request merged**
